### ISSUE TITLE
从deepin15.6升级到15.7后遇到了这个问题

### ISSUE THREAD

**Issue by zhhbo** [zdohnal/system-config-printer#118]
system-config-printer -help
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 84, in <module>
    import jobviewer
  File "/usr/share/system-config-printer/jobviewer.py", line 76, in <module>
    NETWORK_PASSWORD = Secret.Schema.new("org.system.config.printer.store", Secret.SchemaFlags.NONE,
NameError: name 'Secret' is not defined

**Comment by zhhbo** [comment]
打印机打不开，然后，我从终端查看的时候发现了这个问题
我升级到15.7后，把其它以前不用的内核都给卸载了。

**Comment by zhhbo** [comment]
sudo apt install -y gir1.2-secret-1
执行这个命令，解决了

**Comment by zdohnal** [comment]
Closed with commit 42d95b7 , next time please use English when you write an issue.
