### ISSUE TITLE
App does not launch under Python 3.6

### ISSUE THREAD

**Issue by FadeMind** [zdohnal/system-config-printer#51]
I have this output after launch `system-config-printer` in terminal window:
```
[fademind@manjaro ~]$ system-config-printer

(system-config-printer.py:7558): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(system-config-printer.py:7558): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(system-config-printer.py:7558): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 84, in <module>
    import jobviewer
  File "/usr/share/system-config-printer/jobviewer.py", line 57, in <module>
    gi.require_version('GnomeKeyring', '1.0')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeKeyring not available

```
Distro: Manjaro Linux
Desktop: KDE Plasma lastest 5.8.5, Python 3.6.

**Comment by andyrtr** [comment]
Libgnome-keyring is deprecated. Projects should use libsecret instead.

See also Arch Linux report https://bugs.archlinux.org/task/52607 . We're adding a workaround to pass any errors when missing libgnome-keyring.

**Comment by zdohnal** [comment]
Hi, 
this pull request should solve it, please feel free to test it.

**Comment by zdohnal** [comment]
https://github.com/zdohnal/system-config-printer/pull/67
